global:
  resolve_timeout: 5m
  slack_api_url: '<slack_webhook_url>'

route:
  receiver: 'slack-notifications'
  group_by: [alertname, datacenter, app]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    text: 'Triggered: {{ .GroupLabels.alertname }} | App: {{ .GroupLabels.app }}'
    send_resolved: true
